version: 2
jobs:
  build1:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: AngularCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
  build2:
    docker:
      - image: circleci/10.15.3-browsers
    steps:
      - run: xvfb-run -a npm run test -- --watch=false --no-progress --browsers=ChromeHeadless

workflows:
  version: 2
  build_and_test:
    jobs:
      - build1
      - build2:
          requires:
            - build1
